//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelixToolkit.Wpf.SharpDX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelixToolkit.Wpf.SharpDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csParticleInsert {
            get {
                object obj = ResourceManager.GetObject("csParticleInsert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] csParticleUpdate {
            get {
                object obj = ResourceManager.GetObject("csParticleUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dsMeshTriTessellation {
            get {
                object obj = ResourceManager.GetObject("dsMeshTriTessellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gsBillboard {
            get {
                object obj = ResourceManager.GetObject("gsBillboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gsLine {
            get {
                object obj = ResourceManager.GetObject("gsLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gsMeshNormalVector {
            get {
                object obj = ResourceManager.GetObject("gsMeshNormalVector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gsParticle {
            get {
                object obj = ResourceManager.GetObject("gsParticle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gsPoint {
            get {
                object obj = ResourceManager.GetObject("gsPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hsMeshTriTessellation {
            get {
                object obj = ResourceManager.GetObject("hsMeshTriTessellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psBillboardText {
            get {
                object obj = ResourceManager.GetObject("psBillboardText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psBillboardTextOIT {
            get {
                object obj = ResourceManager.GetObject("psBillboardTextOIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psColor {
            get {
                object obj = ResourceManager.GetObject("psColor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psDepthStencilOnly {
            get {
                object obj = ResourceManager.GetObject("psDepthStencilOnly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psDiffuseMap {
            get {
                object obj = ResourceManager.GetObject("psDiffuseMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectBloomBlurHorizontal {
            get {
                object obj = ResourceManager.GetObject("psEffectBloomBlurHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectBloomBlurVertical {
            get {
                object obj = ResourceManager.GetObject("psEffectBloomBlurVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectBloomCombine {
            get {
                object obj = ResourceManager.GetObject("psEffectBloomCombine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectBloomExtract {
            get {
                object obj = ResourceManager.GetObject("psEffectBloomExtract", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectGaussianBlurHorizontal {
            get {
                object obj = ResourceManager.GetObject("psEffectGaussianBlurHorizontal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectGaussianBlurVertical {
            get {
                object obj = ResourceManager.GetObject("psEffectGaussianBlurVertical", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectMeshBorderHighlight {
            get {
                object obj = ResourceManager.GetObject("psEffectMeshBorderHighlight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectMeshDiffuseXRayGrid {
            get {
                object obj = ResourceManager.GetObject("psEffectMeshDiffuseXRayGrid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectMeshXRay {
            get {
                object obj = ResourceManager.GetObject("psEffectMeshXRay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectMeshXRayGrid {
            get {
                object obj = ResourceManager.GetObject("psEffectMeshXRayGrid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectOutlineQuad {
            get {
                object obj = ResourceManager.GetObject("psEffectOutlineQuad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectOutlineQuadStencil {
            get {
                object obj = ResourceManager.GetObject("psEffectOutlineQuadStencil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psEffectOutlineQualFinal {
            get {
                object obj = ResourceManager.GetObject("psEffectOutlineQualFinal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psFXAA {
            get {
                object obj = ResourceManager.GetObject("psFXAA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psLine {
            get {
                object obj = ResourceManager.GetObject("psLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psLineColor {
            get {
                object obj = ResourceManager.GetObject("psLineColor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psLuma {
            get {
                object obj = ResourceManager.GetObject("psLuma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshBlinnPhong {
            get {
                object obj = ResourceManager.GetObject("psMeshBlinnPhong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshBlinnPhongOIT {
            get {
                object obj = ResourceManager.GetObject("psMeshBlinnPhongOIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshBlinnPhongOITQuad {
            get {
                object obj = ResourceManager.GetObject("psMeshBlinnPhongOITQuad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshClipPlaneBackface {
            get {
                object obj = ResourceManager.GetObject("psMeshClipPlaneBackface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshClipPlaneQuad {
            get {
                object obj = ResourceManager.GetObject("psMeshClipPlaneQuad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshColorStripe {
            get {
                object obj = ResourceManager.GetObject("psMeshColorStripe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshDiffuseMapOIT {
            get {
                object obj = ResourceManager.GetObject("psMeshDiffuseMapOIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psMeshXRay {
            get {
                object obj = ResourceManager.GetObject("psMeshXRay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psNormals {
            get {
                object obj = ResourceManager.GetObject("psNormals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psParticle {
            get {
                object obj = ResourceManager.GetObject("psParticle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psParticleOIT {
            get {
                object obj = ResourceManager.GetObject("psParticleOIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psPoint {
            get {
                object obj = ResourceManager.GetObject("psPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psPositions {
            get {
                object obj = ResourceManager.GetObject("psPositions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psScreenDup {
            get {
                object obj = ResourceManager.GetObject("psScreenDup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psShadow {
            get {
                object obj = ResourceManager.GetObject("psShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psSkybox {
            get {
                object obj = ResourceManager.GetObject("psSkybox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psViewCube {
            get {
                object obj = ResourceManager.GetObject("psViewCube", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psWireframe {
            get {
                object obj = ResourceManager.GetObject("psWireframe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] psWireframeOIT {
            get {
                object obj = ResourceManager.GetObject("psWireframeOIT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBillboard {
            get {
                object obj = ResourceManager.GetObject("vsBillboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBillboardInstancing {
            get {
                object obj = ResourceManager.GetObject("vsBillboardInstancing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBoneSkinning {
            get {
                object obj = ResourceManager.GetObject("vsBoneSkinning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBoneSkinningShadow {
            get {
                object obj = ResourceManager.GetObject("vsBoneSkinningShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBoneSkinningTessellation {
            get {
                object obj = ResourceManager.GetObject("vsBoneSkinningTessellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsBoneSkinningWireframe {
            get {
                object obj = ResourceManager.GetObject("vsBoneSkinningWireframe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsCubeMap {
            get {
                object obj = ResourceManager.GetObject("vsCubeMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshBatched {
            get {
                object obj = ResourceManager.GetObject("vsMeshBatched", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshBatchedShadow {
            get {
                object obj = ResourceManager.GetObject("vsMeshBatchedShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshBatchedWireframe {
            get {
                object obj = ResourceManager.GetObject("vsMeshBatchedWireframe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshClipPlane {
            get {
                object obj = ResourceManager.GetObject("vsMeshClipPlane", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshClipPlaneQuad {
            get {
                object obj = ResourceManager.GetObject("vsMeshClipPlaneQuad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshDefault {
            get {
                object obj = ResourceManager.GetObject("vsMeshDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshInstancing {
            get {
                object obj = ResourceManager.GetObject("vsMeshInstancing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshInstancingTessellation {
            get {
                object obj = ResourceManager.GetObject("vsMeshInstancingTessellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshOutlinePass1 {
            get {
                object obj = ResourceManager.GetObject("vsMeshOutlinePass1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshOutlineScreenQuad {
            get {
                object obj = ResourceManager.GetObject("vsMeshOutlineScreenQuad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshShadow {
            get {
                object obj = ResourceManager.GetObject("vsMeshShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshTessellation {
            get {
                object obj = ResourceManager.GetObject("vsMeshTessellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsMeshWireframe {
            get {
                object obj = ResourceManager.GetObject("vsMeshWireframe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsParticle {
            get {
                object obj = ResourceManager.GetObject("vsParticle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsPoint {
            get {
                object obj = ResourceManager.GetObject("vsPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsPointShadow {
            get {
                object obj = ResourceManager.GetObject("vsPointShadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsScreenDup {
            get {
                object obj = ResourceManager.GetObject("vsScreenDup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsScreenDupCursor {
            get {
                object obj = ResourceManager.GetObject("vsScreenDupCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vsSkybox {
            get {
                object obj = ResourceManager.GetObject("vsSkybox", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
