global using Vector3 = System.Numerics.Vector3;
global using Vector2 = System.Numerics.Vector2;
global using Vector4 = System.Numerics.Vector4;
global using Matrix = System.Numerics.Matrix4x4;
global using Matrix3x2 = System.Numerics.Matrix3x2;
global using Plane = System.Numerics.Plane;
global using Quaternion = System.Numerics.Quaternion;
global using Point = System.Numerics.Vector2;
global using Point3D = System.Numerics.Vector3;
global using Vector3D = System.Numerics.Vector3;
global using HelixToolkit.Maths;