#if WINUI
global using Microsoft.UI.Text;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Input;
global using Windows.Foundation;
global using Windows.UI.Text;
global using Vector3D = SharpDX.Vector3;
global using Point3D = SharpDX.Vector3;
global using Size3D = SharpDX.Vector3;
global using Quaternion = SharpDX.Quaternion;
global using Point = Windows.Foundation.Point;
global using UIColor = Windows.UI.Color;
global using UIColors = Microsoft.UI.Colors;
global using FrameworkContentElement = Microsoft.UI.Xaml.FrameworkElement;
global using FrameworkControl = Microsoft.UI.Xaml.Controls.Control;
global using Animatable = Microsoft.UI.Xaml.DependencyObject;
global using Freezable = Microsoft.UI.Xaml.DependencyObject;
#else
//global using System.Windows;
//global using System.Windows.Controls;
global using DependencyProperty = System.Windows.DependencyProperty;
global using PropertyMetadata = System.Windows.PropertyMetadata;
global using ItemsControl = System.Windows.Controls.ItemsControl;
global using Vector3D = System.Windows.Media.Media3D.Vector3D;
global using Point3D = System.Windows.Media.Media3D.Point3D;
global using Size3D = System.Windows.Media.Media3D.Size3D;
global using Quaternion = SharpDX.Quaternion;
global using Matrix3D = System.Windows.Media.Media3D.Matrix3D;
global using Transform3D = System.Windows.Media.Media3D.Transform3D;
global using Transform3DGroup = System.Windows.Media.Media3D.Transform3DGroup;
global using Point = System.Windows.Point;
global using UIMatrix = System.Windows.Media.Matrix;
global using UIColor = System.Windows.Media.Color;
global using UIColors = System.Windows.Media.Colors;
global using FrameworkContentElement = System.Windows.FrameworkContentElement;
global using FrameworkControl = System.Windows.FrameworkContentElement;
global using Animatable = System.Windows.Media.Animation.Animatable;
global using Freezable = System.Windows.Freezable;
#endif
